### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by caseyg** [caseyg/unlikelyengineering#34]
- Design questions
  - [x] Footer with comments / email / contact form
  - [ ] ~~~SEO, analytics, re: question about search terms~~~ #43
  - [x] Color: more sea/coral
  - [x] GIF thumbnails #3
- Todo
  - Global
    - [x] Add contact footer?
    - [x] Drop in texts one more time
    - [ ] ~~~A11y project checklist~~~ #12 
    - [x] Double check photos for ID #33
    - [ ] ~~~Enable caching~~~ #6
    - [ ] ~~~Trigger iOS read view~~~ #44
  - Homepage
    - [x] Update template
    - [ ] ~~~Implement new parallax~~~ #45
  - Adaptations
    - [x] Rename verbs to actions
    - [x] Handwriting sprite #9
    - [x] Remove second Turn and add the missing verb Scratch
    - [ ] ~~~Clean up photoshop clipping~~~ #46
    - [x] Update template
    - [x] Drop in Michael's edits from this week
  - Manifesto/About
    - [x] Update templates
- Facebook
  - [ ] ~~~Schedule posts~~~ #47

**Comment by caseyg** [comment]
adding separate issues for remaining fixes
